export const Users = [
    {
      id: 1,
      nombre: 'Wilmette',
      apellido: 'Maasz',
      email: 'wmaasz0@jalbum.net',
      telefono: '130-309-6439',
    },
    {
      id: 2,
      nombre: 'Morry',
      apellido: 'Heater',
      email: 'mheater1@yale.edu',
      telefono: '814-809-2958',
    },
    {
      id: 3,
      nombre: 'Laverne',
      apellido: 'MacMorland',
      email: 'lmacmorland2@webnode.com',
      telefono: '271-342-7249',
    },
    {
      id: 4,
      nombre: 'Cindee',
      apellido: 'De Freitas',
      email: 'cdefreitas3@privacy.gov.au',
      telefono: '617-624-6967',
    },
    {
      id: 5,
      nombre: 'Carole',
      apellido: 'Reffe',
      email: 'creffe4@nih.gov',
      telefono: '738-966-3137',
    },
    {
      id: 6,
      nombre: 'Ansla',
      apellido: 'Iwanicki',
      email: 'aiwanicki5@pagesperso-orange.fr',
      telefono: '716-371-2467',
    },
    {
      id: 7,
      nombre: 'Herold',
      apellido: 'Mungham',
      email: 'hmungham6@goodreads.com',
      telefono: '659-298-5396',
    },
    {
      id: 8,
      nombre: 'Marcela',
      apellido: 'Gomez',
      email: 'mgomez7@example.com',
      telefono: '123-456-7890',
    },
    {
      id: 9,
      nombre: 'Eduardo',
      apellido: 'Martinez',
      email: 'emartinez8@example.com',
      telefono: '987-654-3210',
    },
    {
      id: 10,
      nombre: 'Laura',
      apellido: 'Hernandez',
      email: 'lhernandez9@example.com',
      telefono: '555-555-5555',
    },
    {
      id: 11,
      nombre: 'Juan',
      apellido: 'Lopez',
      email: 'jlopez10@example.com',
      telefono: '111-222-3333',
    },
    {
      id: 12,
      nombre: 'Ana',
      apellido: 'Rodriguez',
      email: 'arodriguez11@example.com',
      telefono: '444-555-6666',
    },
    {
      id: 13,
      nombre: 'Carlos',
      apellido: 'Garcia',
      email: 'cgarcia12@example.com',
      telefono: '777-888-9999',
    },
    {
      id: 14,
      nombre: 'Maria',
      apellido: 'Perez',
      email: 'mperez13@example.com',
      telefono: '999-888-7777',
    },
    {
      id: 15,
      nombre: 'Luis',
      apellido: 'Sanchez',
      email: 'lsanchez14@example.com',
      telefono: '333-222-1111',
    },
    {
      id: 16,
      nombre: 'Elena',
      apellido: 'Gonzalez',
      email: 'egonzalez15@example.com',
      telefono: '666-555-4444',
    },
    {
      id: 17,
      nombre: 'Pablo',
      apellido: 'Hernandez',
      email: 'phernandez16@example.com',
      telefono: '111-222-3333',
    },
    {
      id: 18,
      nombre: 'Isabel',
      apellido: 'Martinez',
      email: 'imartinez17@example.com',
      telefono: '444-555-6666',
    },
    {
      id: 19,
      nombre: 'David',
      apellido: 'Jimenez',
      email: 'djimenez18@example.com',
      telefono: '777-888-9999',
    },
    {
      id: 20,
      nombre: 'Carmen',
      apellido: 'Lopez',
      email: 'clopez19@example.com',
      telefono: '999-888-7777',
    }
    
    
    
  
  ];